# Use PHP 7.3 by replacing "php72" below with "php73"
runtime: php72

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /(.*\.(gif|png|jpg|htm|html|css|js))$
    static_files: aicotest/\1
    upload: aicotest/.*\.(gif|png|jpg|htm|html|css|js)$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php
